export const PERMISSIONS = {
  // ESCOLTA
  ESCOLTA_LIST: 'PxpYRQba',
  ESCOLTA_CREATE: 'PxpYRQba',
  ESCOLTA_UPDATE: 'PxpYRQba',
  ESCOLTA_DELETE: 'PxpYRQba',
  ESCOLTA_VALIDATE: 'PxpYRQba',
  BODYGUARDS_VIEW: 'PxpYRQba',

  // GEOCERCAS
  GEOCERCAS_DETAILS: '7R1vGpVN',
  GEOCERCAS_LIST: 'O2Qdej9M',
  GEOFENCES_VIEW: 'O2Qdej9M',
  GEOCERCAS_EDIT: 'V7QowQkD',
  GEOCERCAS_DELETE: 'gapyYprY',
  GEOCERCAS_CREATE: 'yDpLO1Xm',

  // HARDWARE
  HARDWARE_LIST: 'r01A91WP',
  HARDWARE_VIEW: 'r01A91WP',
  HARDWARE_CREATE: 'r01A91WP',
  HARDWARE_EDIT: 'r01A91WP',
  HARDWARE_DELETE: 'r01A91WP',
  HARDWARE_ASSIGN: 'r01A91WP',
  HARDWARE_COMMANDS: 'r01A91WP',

  // ROLES
  ROLES_EDIT: '2J1mwQa6',
  ROLES_CREATE: 'Jm1gBj8w',
  ROLES_ASSIGN: 'W4jJW1JG',
  ROLES_DELETE: 'rnjWvQED',
  ROLES_LIST: 'vVj9gpd3',
  ROLES_VIEW: 'vVj9gpd3',

  // RUTAS
  RUTAS_CHANGE_STATUS: '2njwojZN',
  RUTAS_CREATE: 'LOjrzjYX',
  RUTAS_EDIT: 'WN1ELjZD',
  RUTAS_LIST: 'yPQPn10V',
  ROUTES_VIEW: 'yPQPn10V',
  RUTAS_DELETE: 'WN1ELjZD',

  // SERVICE
  SERVICE_HISTORY: '8EpaOLj2',
  SERVICE_CREATE: 'Jm1gBBj8',
  SERVICE_LIST_DASH: 'rnjW5vpE',
  SERVICE_LIST_TABLE: 'vVj9Rg1d',

  // USUARIOS
  USERS_EDIT: '8EpaL127',
  USERS_CREATE: 'BDjMxQ8K',
  USERS_LIST: 'PEjxE1rz',
  USERS_VIEW: 'PEjxE1rz',
  USERS_DELETE: 'VYQq9Qbz',

  // VEHICULOS
  VEHICULOS_EDIT: '2aQN81vy',
  VEHICULOS_UPDATE: '2aQN81vy',
  VEHICULOS_LIST: '7zj6EQRk',
  VEHICULOS_CREATE: 'rzpnWQl2',
  VEHICULOS_DELETE: 'w3Q48Qz0',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionId = typeof PERMISSIONS[PermissionKey] | string;

