export const PERMISSIONS = {
  // ALERT
  ALERT_SOLVENTAR: '6qjeqWjW',
  ALERT_HISTORIAL: 'r01AG9QW',

  // ESCOLTA
  ESCOLTA_ASSIGN_VEHICLE: '67pD2j2X',
  ESCOLTA_DELETE: '7epKYjNV',
  ESCOLTA_UPDATE: 'Ez1kqQLB',
  ESCOLTA_LIST: 'PxpYRQba',
  ESCOLTA_VALIDATE: 'RzQ3WQdX',
  ESCOLTA_CREATE: 'a6QV81LX',
  ESCOLTA_ASSIGN_HARDWARE: 'bnjOkj42',

  // GEOCERCAS
  GEOCERCAS_DETAILS: '7R1vGpVN',
  GEOCERCAS_LIST: 'O2Qdej9M',
  GEOCERCAS_EDIT: 'V7QowQkD',
  GEOCERCAS_DELETE: 'gapyYprY',
  GEOCERCAS_CREATE: 'yDpLO1Xm',

  // HARDWARE
  HARDWARE_DELETE: '5rplqQ6w',
  HARDWARE_CREATE: '6qjeWpWe',
  HARDWARE_EDIT: '9E189pqG',
  HARDWARE_COMMANDS: 'BOpRDje8', // Abrir candado
  HARDWARE_LIST_FAMILIES: 'eOp0vjoa',
  HARDWARE_LIST_SIMPLE: 'ln1b5jq8',
  HARDWARE_HISTORY_MAP: 'oWp2XjD4',
  HARDWARE_LIST: 'r01A91WP',

  // ROLES
  ROLES_EDIT: '2J1mwQa6',
  ROLES_CREATE: 'Jm1gBj8w',
  ROLES_ASSIGN: 'W4jJW1JG',
  ROLES_VIEW_PERMISSIONS: 'W81Bb1Z4',
  ROLES_DELETE: 'rnjWvQED',
  ROLES_LIST: 'vVj9gpd3',

  // RUTAS
  RUTAS_CHANGE_STATUS: '2njwojZN',
  RUTAS_CREATE: 'LOjrzjYX',
  RUTAS_EDIT: 'WN1ELjZD',
  RUTAS_LIST: 'yPQPn10V',

  // SERVICE
  SERVICE_ASSIGN_RESOURCES: '2J1m4wja',
  SERVICE_HISTORY: '8EpaOLj2',
  SERVICE_CHANGE_BODYGUARDS: 'BDjMvx18',
  SERVICE_CREATE: 'Jm1gBBj8',
  SERVICE_CHANGE_VEHICLES: 'PEjxOEQr',
  SERVICE_CHANGE_STATUS: 'VYQqW91b',
  SERVICE_CHANGE_ROUTE: 'W4jJ5WQJ',
  SERVICE_LIST_DASH: 'rnjW5vpE',
  SERVICE_LIST_TABLE: 'vVj9Rg1d',

  // USUARIOS
  USERS_EDIT: '8EpaL127',
  USERS_CREATE: 'BDjMxQ8K',
  USERS_LIST: 'PEjxE1rz',
  USERS_DELETE: 'VYQq9Qbz',

  // VEHICLE BODYGUARD
  VEHICLE_BODYGUARD_LIST: '3oQ7wQEJ',
  VEHICLE_BODYGUARD_DELETE: '501Xy8pK',
  VEHICLE_BODYGUARD_CREATE: 'mOpz2pzw',
  VEHICLE_BODYGUARD_UPDATE: 'nopGej4b',

  // VEHICULOS
  VEHICULOS_EDIT: '2aQN81vy',
  VEHICULOS_LIST: '7zj6EQRk',
  VEHICULOS_CREATE: 'rzpnWQl2',
  VEHICULOS_DELETE: 'w3Q48Qz0',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionId = typeof PERMISSIONS[PermissionKey] | string;


