export const PERMISSIONS = {
  // ROLES
  ROLES_CREATE: 1,
  ROLES_LIST: 2,
  ROLES_EDIT: 3,
  ROLES_DELETE: 4,
  ROLES_ASSIGN: 5,
  
  // USUARIOS
  USERS_CREATE: 6,
  USERS_LIST: 7,
  USERS_EDIT: 8,
  USERS_DELETE: 9,
  
  // HARDWARE
  HARDWARE_CREATE: 10,
  HARDWARE_LIST: 11,
  HARDWARE_EDIT: 12,
  HARDWARE_DELETE: 13,
  HARDWARE_ASSIGN: 14,
  HARDWARE_COMMANDS: 15,
  
  // ESCOLTA
  ESCOLTA_CREATE: 16,
  ESCOLTA_UPDATE: 17,
  ESCOLTA_DELETE: 18,
  ESCOLTA_VALIDATE: 19,
  ESCOLTA_LIST: 20,
  
  // RUTAS
  RUTAS_CREATE: 21,
  RUTAS_LIST: 22,
  RUTAS_EDIT: 23,
  RUTAS_DELETE: 24,
  
  // GEOCERCAS
  GEOCERCAS_CREATE: 25,
  GEOCERCAS_LIST: 26,
  GEOCERCAS_EDIT: 27,
  GEOCERCAS_DELETE: 28,
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionId = typeof PERMISSIONS[PermissionKey];
